//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spellmaker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Test")]
        public string GoogleSheetID {
            get {
                return ((string)(this["GoogleSheetID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Spellmaker.SettingsData SettingsObj {
            get {
                return ((global::Spellmaker.SettingsData)(this["SettingsObj"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SelectedPrev {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SelectedPrev"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[{&quot;Item1&quot;:&quot;Name&quot;,&quot;Item2&quot;:{&quot;Defines&quot;:null," +
            "&quot;ExtractArea&quot;:null,&quot;FrameIndex&quot;:null,&quot;FrameCount&quot;:" +
            "null,&quot;Height&quot;:300,&quot;UseMonochrome&quot;:false,&quot;Width&quot;:50" +
            "0,&quot;Affine&quot;:null,&quot;AntiAlias&quot;:true,&quot;BackgroundColor&quot;" +
            ":{&quot;A&quot;:0,&quot;B&quot;:65535,&quot;G&quot;:65535,&quot;K&quot;:0,&quot;" +
            "R&quot;:65535},&quot;BorderColor&quot;:{&quot;A&quot;:65535,&quot;B&quot;:57311," +
            "&quot;G&quot;:57311,&quot;K&quot;:0,&quot;R&quot;:57311},&quot;ColorSpace&quot;:" +
            "0,&quot;ColorType&quot;:0,&quot;Compression&quot;:0,&quot;Debug&quot;:false,&quo" +
            "t;Density&quot;:null,&quot;Depth&quot;:0,&quot;Endian&quot;:0,&quot;FillColor&qu" +
            "ot;:{&quot;A&quot;:65535,&quot;B&quot;:0,&quot;G&quot;:0,&quot;K&quot;:0,&quot;R" +
            "&quot;:0},&quot;FillPattern&quot;:null,&quot;FillRule&quot;:1,&quot;Font&quot;:&" +
            "quot;Gabriola&quot;,&quot;FontFamily&quot;:null,&quot;FontPointsize&quot;:75.0,&" +
            "quot;FontStyle&quot;:0,&quot;FontWeight&quot;:0,&quot;Format&quot;:0,&quot;Page&" +
            "quot;:null,&quot;StrokeAntiAlias&quot;:true,&quot;StrokeColor&quot;:{&quot;A&quo" +
            "t;:0,&quot;B&quot;:65535,&quot;G&quot;:65535,&quot;K&quot;:0,&quot;R&quot;:65535" +
            "},&quot;StrokeDashArray&quot;:null,&quot;StrokeDashOffset&quot;:0.0,&quot;Stroke" +
            "LineCap&quot;:1,&quot;StrokeLineJoin&quot;:1,&quot;StrokeMiterLimit&quot;:10,&qu" +
            "ot;StrokePattern&quot;:null,&quot;StrokeWidth&quot;:1.0,&quot;TextAntiAlias&quot" +
            ";:true,&quot;TextDirection&quot;:0,&quot;TextEncoding&quot;:null,&quot;TextGravi" +
            "ty&quot;:4,&quot;TextInterlineSpacing&quot;:0.0,&quot;TextInterwordSpacing&quot;" +
            ":0.0,&quot;TextKerning&quot;:0.0,&quot;TextUnderColor&quot;:{&quot;A&quot;:0,&qu" +
            "ot;B&quot;:0,&quot;G&quot;:0,&quot;K&quot;:0,&quot;R&quot;:0},&quot;Verbose&quot" +
            ";:false},&quot;Item3&quot;:&quot;250, 0&quot;},{&quot;Item1&quot;:&quot;Name&quo" +
            "t;,&quot;Item2&quot;:{&quot;Defines&quot;:null,&quot;ExtractArea&quot;:null,&quo" +
            "t;FrameIndex&quot;:null,&quot;FrameCount&quot;:null,&quot;Height&quot;:500,&quot" +
            ";UseMonochrome&quot;:false,&quot;Width&quot;:500,&quot;Affine&quot;:null,&quot;A" +
            "ntiAlias&quot;:true,&quot;BackgroundColor&quot;:{&quot;A&quot;:0,&quot;B&quot;:6" +
            "5535,&quot;G&quot;:65535,&quot;K&quot;:0,&quot;R&quot;:65535},&quot;BorderColor&" +
            "quot;:{&quot;A&quot;:65535,&quot;B&quot;:57311,&quot;G&quot;:57311,&quot;K&quot;" +
            ":0,&quot;R&quot;:57311},&quot;ColorSpace&quot;:0,&quot;ColorType&quot;:0,&quot;C" +
            "ompression&quot;:0,&quot;Debug&quot;:false,&quot;Density&quot;:null,&quot;Depth&" +
            "quot;:0,&quot;Endian&quot;:0,&quot;FillColor&quot;:{&quot;A&quot;:65535,&quot;B&" +
            "quot;:0,&quot;G&quot;:0,&quot;K&quot;:0,&quot;R&quot;:0},&quot;FillPattern&quot;" +
            ":null,&quot;FillRule&quot;:1,&quot;Font&quot;:&quot;Gabriola&quot;,&quot;FontFam" +
            "ily&quot;:null,&quot;FontPointsize&quot;:60.0,&quot;FontStyle&quot;:0,&quot;Font" +
            "Weight&quot;:0,&quot;Format&quot;:0,&quot;Page&quot;:null,&quot;StrokeAntiAlias&" +
            "quot;:true,&quot;StrokeColor&quot;:{&quot;A&quot;:0,&quot;B&quot;:65535,&quot;G&" +
            "quot;:65535,&quot;K&quot;:0,&quot;R&quot;:65535},&quot;StrokeDashArray&quot;:nul" +
            "l,&quot;StrokeDashOffset&quot;:0.0,&quot;StrokeLineCap&quot;:1,&quot;StrokeLineJ" +
            "oin&quot;:1,&quot;StrokeMiterLimit&quot;:10,&quot;StrokePattern&quot;:null,&quot" +
            ";StrokeWidth&quot;:1.0,&quot;TextAntiAlias&quot;:true,&quot;TextDirection&quot;:" +
            "0,&quot;TextEncoding&quot;:null,&quot;TextGravity&quot;:4,&quot;TextInterlineSpa" +
            "cing&quot;:0.0,&quot;TextInterwordSpacing&quot;:0.0,&quot;TextKerning&quot;:0.0," +
            "&quot;TextUnderColor&quot;:{&quot;A&quot;:0,&quot;B&quot;:0,&quot;G&quot;:0,&quo" +
            "t;K&quot;:0,&quot;R&quot;:0},&quot;Verbose&quot;:false},&quot;Item3&quot;:&quot;" +
            "300, 0&quot;},{&quot;Item1&quot;:&quot;Name&quot;,&quot;Item2&quot;:{&quot;Defin" +
            "es&quot;:null,&quot;ExtractArea&quot;:null,&quot;FrameIndex&quot;:null,&quot;Fra" +
            "meCount&quot;:null,&quot;Height&quot;:500,&quot;UseMonochrome&quot;:false,&quot;" +
            "Width&quot;:250,&quot;Affine&quot;:null,&quot;AntiAlias&quot;:true,&quot;Backgro" +
            "undColor&quot;:{&quot;A&quot;:0,&quot;B&quot;:65535,&quot;G&quot;:65535,&quot;K&" +
            "quot;:0,&quot;R&quot;:65535},&quot;BorderColor&quot;:{&quot;A&quot;:65535,&quot;" +
            "B&quot;:57311,&quot;G&quot;:57311,&quot;K&quot;:0,&quot;R&quot;:57311},&quot;Col" +
            "orSpace&quot;:0,&quot;ColorType&quot;:0,&quot;Compression&quot;:0,&quot;Debug&qu" +
            "ot;:false,&quot;Density&quot;:null,&quot;Depth&quot;:0,&quot;Endian&quot;:0,&quo" +
            "t;FillColor&quot;:{&quot;A&quot;:65535,&quot;B&quot;:0,&quot;G&quot;:0,&quot;K&q" +
            "uot;:0,&quot;R&quot;:0},&quot;FillPattern&quot;:null,&quot;FillRule&quot;:1,&quo" +
            "t;Font&quot;:&quot;Gabriola&quot;,&quot;FontFamily&quot;:null,&quot;FontPointsiz" +
            "e&quot;:18.0,&quot;FontStyle&quot;:0,&quot;FontWeight&quot;:0,&quot;Format&quot;" +
            ":0,&quot;Page&quot;:null,&quot;StrokeAntiAlias&quot;:true,&quot;StrokeColor&quot" +
            ";:{&quot;A&quot;:0,&quot;B&quot;:65535,&quot;G&quot;:65535,&quot;K&quot;:0,&quot" +
            ";R&quot;:65535},&quot;StrokeDashArray&quot;:null,&quot;StrokeDashOffset&quot;:0." +
            "0,&quot;StrokeLineCap&quot;:1,&quot;StrokeLineJoin&quot;:1,&quot;StrokeMiterLimi" +
            "t&quot;:10,&quot;StrokePattern&quot;:null,&quot;StrokeWidth&quot;:1.0,&quot;Text" +
            "AntiAlias&quot;:true,&quot;TextDirection&quot;:0,&quot;TextEncoding&quot;:null,&" +
            "quot;TextGravity&quot;:5,&quot;TextInterlineSpacing&quot;:0.0,&quot;TextInterwor" +
            "dSpacing&quot;:0.0,&quot;TextKerning&quot;:0.0,&quot;TextUnderColor&quot;:{&quot" +
            ";A&quot;:0,&quot;B&quot;:0,&quot;G&quot;:0,&quot;K&quot;:0,&quot;R&quot;:0},&quo" +
            "t;Verbose&quot;:false},&quot;Item3&quot;:&quot;75, 250&quot;}]")]
        public string DeaultTextSettings {
            get {
                return ((string)(this["DeaultTextSettings"]));
            }
        }
    }
}
